### ISSUE TITLE
i3d model checkpoint does not restore

### ISSUE THREAD

**Issue by rahman-mdatiqur** [princeton-vl/d3dhelper#2]
Hello @jonathancstroud ,

thank you so much for the wonderful demo code, specially the model checkpoints. While s3dg checkpoints can be successfully loaded and used for the demo, I was not able to load i3d checkpoints (_NET_TYPE='i3d') that I downloaded from the Google drive link you mentioned on the notebook. Below is the full error dump. 

Can you please help pointing out what's causing the script to fail to load the i3d checkpoints?

---------------------------------------------------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

NotFoundError: Key InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1545         sess.run(self.saver_def.restore_op_name,
-> 1546                  {self.saver_def.filename_tensor_name: save_path})
   1547     except errors.NotFoundError as err:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 

NotFoundError: Key InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at <ipython-input-7-5b6c19f95798>:1)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2787, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-5b6c19f95798>", line 1, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 862, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at <ipython-input-7-5b6c19f95798>:1)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1555       try:
-> 1556         names_to_keys = object_graph_key_mapping(save_path)
   1557       except errors.NotFoundError:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py in object_graph_key_mapping(checkpoint_path)
   1829   object_graph_string = reader.get_tensor(
-> 1830       checkpointable.OBJECT_GRAPH_PROTO_KEY)
   1831   object_graph_proto = (

/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in get_tensor(self, tensor_str)
    370         return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str),
--> 371                                           status)
    372 

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
    529     # Delete the underlying status object from memory otherwise it stays alive

NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-7-5b6c19f95798> in <module>()
      6 
      7 with tf.Session(config=config) as sess:
----> 8     saver.restore(sess, _MODEL_CKPT)
      9 
     10     net_eval_abseiling = sess.run(net, feed_dict={inputs: abseiling})

/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1560         # a helpful message (b/110263146)
   1561         raise _wrap_restore_error_with_msg(
-> 1562             err, "a Variable name or other graph key that is missing")
   1563 
   1564       # This is an object-based checkpoint. We'll print a warning and then do

NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at <ipython-input-7-5b6c19f95798>:1)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.5/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2787, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-5b6c19f95798>", line 1, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 862, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta not found in checkpoint
	 [[node save/RestoreV2 (defined at <ipython-input-7-5b6c19f95798>:1)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/

**Comment by jonathancstroud** [comment]
Hi, thanks for your interest in our work.

It looks like this issue is because some variables are misnamed in the I3D checkpoint. I suspect this is because the checkpoint was made using an earlier version of the code. To fix it, you need to map some of the variables in the checkpoint to new names. Specifically:

all variables starting with `InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_3x3`  in the checkpoint file should be renamed to: `InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3`

I believe you can do this with [tf.train.Saver](https://www.tensorflow.org/api_docs/python/tf/train/Saver#restore) using the `var_list` argument. You will need to pass in a dict which maps the incorrect names in the checkpoint to the correct variables.

Hope this helps!

**Comment by atique81** [comment]
Hello @jonathancstroud ,

thanks for your prompt reply and the suggestion to fix the issue. Just wondering, if I rename the `InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_3x3` to `InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3`, then wouldn't it fail on the variables `InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_3x3`?  

For your reference, below is the list of variables in the model s3dg having the scope of `InceptionV1/Mixed_5b/Branch_2' that I got from using 
`from tensorflow.python.tools import inspect_checkpoint`

-----------------------------------------------------------------------------------------------
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/beta
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/beta/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/beta/Momentum
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/moving_mean
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/moving_mean/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/moving_variance
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/BatchNorm/moving_variance/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/weights
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/weights/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_1x1/weights/Momentum
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/beta/Momentum
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/moving_mean
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/moving_mean/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/moving_variance
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/BatchNorm/moving_variance/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/self_gating/transformer_W/weights
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/self_gating/transformer_W/weights/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/self_gating/transformer_W/weights/Momentum
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/temporal/biases
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/temporal/biases/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/temporal/biases/Momentum
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/temporal/weights
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/temporal/weights/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/temporal/weights/Momentum
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/weights
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/weights/ExponentialMovingAverage
tensor_name:  InceptionV1/Mixed_5b/Branch_2/Conv2d_0b_3x3/weights/Momentum

**Comment by jonathancstroud** [comment]
There shouldn't be any variables named `InceptionV1/Mixed_5b/Branch_2/Conv2d_0a_3x3/...` in any of the checkpoints, except for in the broken I3D checkpoint. In the output you pasted above, the variables are (correctly) named either `Conv2d_0a_1x1` or `Conv2d_0b_3x3`. For I3D, the latter is mistakenly named `Conv2d_0a_3x3`. This was most likely due to a typo in an old version of the code, but it will have no effect on the output. Sorry for the inconvenience!

**Comment by rahman-mdatiqur** [comment]
Yeah, you are absolutely right! I actually deleted the message immediately I noticed that! 

I really appreciate your quick and helpful feedback! One last thing, d3d models should be loaded with s3dg arg_scope right?
